name: media-tools
services:
  cache:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - server
  api:
    build: https://github.com/om3lette/Media-api.git#main:backend
    volumes:
      - api_persistent_data:/api/backend/persistence
      - whisper_models:/root/.cache/whisper
    networks:
      - server
    ports:
      - "8081:8081"
    environment:
      REDIS_CONNECTION_STRING: redis://cache:6379/0
    depends_on:
      - cache

volumes:
  api_persistent_data: {}
  whisper_models: {}
  redis_data: {}

networks:
  server: {}
